typography_spectrum: 0.6325683910399675
color:
  brandStrength: 0.7838995447382331
  lightness: 0.616242780117318
  saturation: 0.049097699113190174
  rhythmicContrast: 0.21761038107797503
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
layout_spectrum: 0.26162728015333414
name: J. Austin Wrench
title: Serial Entrepreneur
